### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by willjasen** [covenanttechnologysolutions/connectwise-rest#1]
I'm using a slightly modified example (with the appropriate cw attributes replaced):

```
var ConnectWiseRest = require('connectwise-rest');

var cw = new ConnectWiseRest({
    companyId: 'company',
    companyUrl: 'your.connectwise.com',
    publicKey: '<public key>',
    privateKey: '<private key>'
});

cw.ServiceDeskAPI.Tickets.getTicketById(1234)
    .then(function (result){
        //do something with results
    })
    .fail(function (error){
        //handle errors
        console.log(error);
    });
```

but I receive the error:

`[SyntaxError: Unexpected token <]`

I can't seem to figure out what I'm missing. Assistance is appreciated!

**Comment by zifu** [comment]
Are you using cloud hosted ConnectWise?

**Comment by willjasen** [comment]
Yes, it is cloud hosted (na.myconnectwise.net)

**Comment by zifu** [comment]
Try using api-na.myconnectwise.net instead.   I hesitated to put that up originally because I only have access to on-prem ConnectWise, and didn't have anyway to verify.  

The error message you're seeing is from the parser, I should update that error message to make more sense.   It returns that error if the result from the page isn't as expected, e.g. HTML.

**Comment by willjasen** [comment]
I tried api-na.myconnectwise.net but same error.

**Comment by zifu** [comment]
I was able to find the correct address.  I added some functionality to override the `entryPoint` in the URL.

You'll need to specify `companyUrl` as `api-na.myconnectwise.net` and `entryPoint` as `v2016_2`.  I've also added some error handling for this case, as well as if the `companyUrl` does not connect or resolve.

**Comment by willjasen** [comment]
It's working for me now, thanks!
