### ISSUE TITLE
How does one get around the CORS policy issue with this lib?

### ISSUE THREAD

**Issue by mikewojtkiewicz** [covenanttechnologysolutions/connectwise-rest#14]
I think I'm using this correctly, but I'm not sure who I get around the CORS policy being blocked when using your library in react. Any ideas?

**Comment by k-grube** [comment]
CORS will block requests to other pages in the browser based on the headers of the requested site.  There might be a way to modify your CWM webserver to allow requests cross-domain. 

That being said, I do not recommend that you run this module in the browser as this will leak your public and private API keys.   It's recommended to run this on the backend (express, hapi, etc) and proxy requests through your own authentication system.
