### ISSUE TITLE
Update Documentation for Cloud Hosted ConnectWise

### ISSUE THREAD

**Issue by keyhole425** [covenanttechnologysolutions/connectwise-rest#17]
Hi there,

I've spent some time fiddling around with the ConnectWise options for a 2019 cloud hosted ConnectWise instance and have finally for it working.  Your documentation is slightly outdated now for Cloud Hosted ConnectWise instances.  The following needs changing:
entryPoint: v2016_2 to entryPoint: v2019_3

There is also a forth cloud-hosted URL that Users may encounter:
'api-staging.connectwisedev.com' - This is used when you have been given demo access to ConnectWise.

I am happy to create a PR with the necessary changes. Let me know if you'd like this.

Thanks,
Kyle

**Comment by k-grube** [comment]
Thanks for the help.  I've added a note to change the entry point to the current hosted version.
