### ISSUE TITLE
Is there a plan to add Phases to the Projects API?

### ISSUE THREAD

**Issue by Zer0dn** [covenanttechnologysolutions/connectwise-rest#18]
The REST model now provides access to the Phases and even deeper parts of Projects but it looks as if presently the API here is only skin deep on the Projects side. Will there be any future updates to include phases and such?

**Comment by k-grube** [comment]
I am working on a refactor that generates most of the bindings from the non-standard open api specifications supplied by ConnectWise.  When this is complete, you'll have access to every API method.   In the mean time, you can manually call `api('/path/to/api', 'METHOD', {params})` for functions that do not have bindings at this time.
