### ISSUE TITLE
get all tickets by status = new 

### ISSUE THREAD

**Issue by subratab0** [covenanttechnologysolutions/connectwise-rest#2]
I am wondering that is there any way to get all tickets by status, by default including status=closed are showing.

**Comment by k-grube** [comment]
You'd have to repeatedly call `ServiceDeskAPI.Tickets.getTickets` and increase the page until there are no more results.  I believe the CW api limits the page size to ~200 or so. 
That function is documented here: https://github.com/covenanttechnologysolutions/connectwise-rest/blob/master/doc.md#Tickets+getTickets
