### ISSUE TITLE
CW has turned on Client ID today

### ISSUE THREAD

**Issue by bur4an** [covenanttechnologysolutions/connectwise-rest#22]
How do i authorise with the new clientid being turned on now ? https://developer.connectwise.com/ClientID

Please help - I have few script based on this module :)

**Comment by k-grube** [comment]
Add `clientId: '<your client id>'` as part of the options object when instantiating the module.  

Example:
```javascript 

const ConnectWise = require('connectwise-rest');

const cw = new ConnectWise({
  clientId: '<your client id>',
 // the rest of your options
})
```
