### ISSUE TITLE
Request to add Params for CompanySite Methods

### ISSUE THREAD

**Issue by Asher978** [covenanttechnologysolutions/connectwise-rest#30]
https://github.com/covenanttechnologysolutions/connectwise-rest/blob/f3fb8b5825e6d7470d1b6761c7b7b0ff000482a7/src/CompanyAPI/CompanySites.js#L57

We are ONLY able to pull 25 sites max as there is no option for the method to take params.

Any idea if this can be added?

**Comment by k-grube** [comment]
Sorry for the delay on this, please check out the new v1 as it includes all API methods for Automate and Manage.
