### ISSUE TITLE
The HTTP resource that matches the request URI does not support the API version '0.0'.

### ISSUE THREAD

**Issue by Anaphylaxis** [covenanttechnologysolutions/connectwise-rest#35]
{"code":"ConnectWiseApi","message":"The HTTP resource that matches the request URI 'custom_url/v4_6_release/apis/3.0/service/tickets/123456/attachChildren' does not support the API version '0.0'."}
I am using the default version 3.0.0 -- the schema states 2021.1 however this returns same error (but API version '2021.1').
It works for basically every request I've found so far except `cw.API.api('/service/tickets/{parentId}/attachChildren')`
Upon further investigation it appears that the "Accept" header being forced to `application/vnd.connectwise.com+json; version=${config.apiVersion}, application/json`, which is causing the issue. Removing the accept header or chaning it to "application/json" resolves this issue. Any ideas? Doesn't feel right to be editing node_modules/connectwise/ConnectWise.js to fix this

**Comment by k-grube** [comment]
Pass in `apiVersion` in the `options` object for your particular instance of CW Manage (e.g. "2021.2").   The default `apiVersion: '3.0.0'` may have been disabled for hosted instances of Manage.
