### ISSUE TITLE
Documentation for ConnectWise.prototype.paginate

### ISSUE THREAD

**Issue by bhubbard** [covenanttechnologysolutions/connectwise-rest#37]
Hi guys, would it be possible to update the readme or documentation to make it clearer on how to use the paginate function. IE. example how to loop thru all companies for example. How could I log to the console each page number?

**Comment by k-grube** [comment]
I'd recommend you roll your own pagination handler for your specific application, however, it's possible to use the one included as follows:
```javascript
function getAllCompanyContacts = (id) => {
  return paginate(
    // reference to function to use
    cwRest.CompanyAPI.Contacts.getContacts,
    // function args
    [{conditions: `company/id = ${id}`}],
    // include a reference to function's module
    cwRest.CompanyAPI.Contacts);
    })
    .then(result => {
      // do something with result
    })
}
```

**Comment by bhubbard** [comment]
@k-grube Thanks. Any specific reasons as to why I should roll my own pagination vs this option?
