### ISSUE TITLE
Missing Alternative Login Options

### ISSUE THREAD

**Issue by DennisRutherford** [covenanttechnologysolutions/connectwise-rest#46]
I know this is built for Node and therefore basically _standalone_ and not meant to be used in the web where this other auth option would be useful. But can we get something changed to support this?

https://developer.connectwise.com/Products/Manage/Developer_Guide

Method 3 - Member ID and Password - Cookie Authentication (Not intended for 3rd party products unless using Hosted API)
This method uses 3 cookie headers.
Cookie: companyName=YourLoginCompany
Cookie: memberHash=Generated by POST to login.aspx or via Hosted API
Cookie: memberId=YourUsername
Cookie: memberContext=web

**Comment by k-grube** [comment]
This library is not meant to be used in the browser, only with API Member authentication.  ConnectWise doesn't recommend using that login method anyway except for making pods.

**Comment by icyfire0573** [comment]
Thank you for the update. As a use case for this I would have a hosted pod that would send out a javascript fetch with the credentials and use those to connect back to the manage instance. 

I understand if you don't want to add this. I can fork it and add the relevant bits myself, can you point me to the file(s) I would need to fuss with to make that authentication work?
