### ISSUE TITLE
Updated QS library because tough-cookie version 2.2.2 dependency has a ReDos vulnerability issue?

### ISSUE THREAD

**Issue by iknowit-dino** [covenanttechnologysolutions/connectwise-rest#5]
Hi, you guys planning to update the qs library? Thanks!

**Comment by k-grube** [comment]
Commit 9cb8fdbfdd55d3808323989a014db29e623cd175 resolves this.  Looks like it was a dependency of request causing the installation warning.

**Comment by iknowit-dino** [comment]
Thanks!
