### ISSUE TITLE
Downloads from /system/documents/{id}/download are corrupted

### ISSUE THREAD

**Issue by robgilbreath** [covenanttechnologysolutions/connectwise-rest#50]
When using SystemAPI.getSystemDocuments, the default axios request settings cause the Manage API to convert any file to UTF-8 encoding, which can corrupt the file (we specifically came across this with .wav attachments). The fix we used is to modify  /dist/Manage.js line 115 to add an Axios interceptor to change the request for this specific endpoint.

```
this.instance.interceptors.request.use((config) => { 
  if (config.url) {
    //check for requests to /system/documents/{id}/download
    const documentDownloadEndpointRegExp = /^\/system\/documents\/[0-9]*\/download$/;
    if (documentDownloadEndpointRegExp.test(config.url)) {
      //replace the string "application/json" with "blob" in the Accept header
      config.headers.Accept = config.headers.Accept.replace('application\/json', 'blob');
      //add response type 'stream' to axios response type
      config.responseType = 'stream';    
    }
  }
  return config;
});
```

I'd do a pull request, but cannot see the source code for generating the Manage.js code.

**Comment by k-grube** [comment]
Probably around here somewhere: https://github.com/covenanttechnologysolutions/connectwise-rest/blob/master/src/Manage.ts#L125

I will adjust and rebuild.

**Comment by robgilbreath** [comment]
I screwed up when browsing the ts structure. Added a pull request and can help if you want to add to tests.
