### ISSUE TITLE
getTicketById problem passing string or int

### ISSUE THREAD

**Issue by qtconsultants** [covenanttechnologysolutions/connectwise-rest#9]
I am probably doing something wrong here, but I have the following...
```javascript
cw.ServiceDeskAPI.Tickets.getTickets({conditions:'status/name="Complete"', 'orderBy' : 'id desc','pageSize' : 1000, 'page' : 1})
        .then(function (res) { 
		var ticketID = JSON.stringify(res);
		var ticketID = ticketID.substr(7,5);
		var ticketNum = ticketID;
		console.log(ticketNum);
	
 	})
        .catch(function (err) { console.log(err); });

cw.ServiceDeskAPI.Tickets.getTicketById(ticketNum)
        .then(function (res) { 
		var fs = require('fs');
		fs.writeFile("./test.xml", JSON.stringify(res), function(err) {
   		if(err) {
        		return console.log(err);
    			}
			console.log("The file was saved!");
			});
	
 	})
        .catch(function (err) { console.log(err); });
```
When I pass the ticketNum variable to the second call I get a json response error.  If I type the ticket number into the getTicketById everything is fine, but if I pass a variable it fails.  Any ideas?

**Comment by k-grube** [comment]
You don't need to parse the response.  It's already an object or an array.   Per the [documentation](https://github.com/covenanttechnologysolutions/connectwise-rest/blob/master/doc.md#Tickets+getTickets) this method returns an array of Ticket objects. 
If you want a list of ticket numbers, you can do something like
```Tickets.getTickets({conditions}).then(tickets => console.log(tickets.map(ticket => ticket.id)));```

**Comment by qtconsultants** [comment]
Nice! Thank you so much!

On Aug 3, 2018 1:18 PM, Kevin Grube <notifications@github.com> wrote:

You don't need to parse the response. It's already an object or an array. Per the documentation<https://github.com/covenanttechnologysolutions/connectwise-rest/blob/master/doc.md#Tickets+getTickets> this method returns an array of Ticket objects.
If you want a list of ticket numbers, you can do something like
Tickets.getTickets({conditions}).then(tickets => console.log(tickets.map(ticket => ticket.id)));
